version: '3'
services:
    python:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - "127.0.0.1:8899:8899"
        volumes:
            - ./samples:/home/jovyan/work
