version: '3'
services:
    python-dev:
        build:
            context: ./
            dockerfile: ./Dockerfile-dev
        environment: 
            - PYTHONPATH=/home/jovyan/work
        ports:
            - "127.0.0.1:8899:8899"
        volumes:
            - .:/home/jovyan/work:cached
