version: '3'
services:
    python-dev:
        build:
            context: ./
            dockerfile: ./Dockerfile-dev
        ports:
            - "8889:8889"
        volumes:
            - .:/home/jovyan/work:cached
