version: '3'
services:
    python:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - "8888:8888"
        volumes:
            - ./samples:/home/jovyan/work
