# Copyright Ryo Ikota
ARG BASE_CONTAINER=jupyter/scipy-notebook:python-3.9.13
FROM $BASE_CONTAINER


USER $NB_UID
COPY requirements-conda.txt /tmp/
RUN mamba install --yes --file /tmp/requirements-conda.txt && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

WORKDIR $HOME/work
CMD ["start.sh", "jupyter", "lab", "--port=8899", "--LabApp.token=''"]
