# Copyright Ryo Ikota
ARG BASE_CONTAINER=jupyter/scipy-notebook:29edefbcb06a
FROM $BASE_CONTAINER

# ENV PKGDIR=$HOME/package

# COPY --chown=$NB_USER:$NB_GID setup.py $PKGDIR/ 
# COPY --chown=$NB_USER:$NB_GID pseudospec/ $PKGDIR/pseudospec 
# COPY --chown=$NB_USER:$NB_GID tests/ $HOME/tests 
USER $NB_UID
RUN conda install --yes nose pytest && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
# RUN cd $PKGDIR ; python setup.py install --record files.txt
WORKDIR $HOME/work
CMD ["start.sh", "jupyter", "notebook", "--port=8889", "--NotebookApp.token=''"]
